---
title: "Data Pre-Processing"
subtitle: "STAT 692: California Public Libraries"
author: "Kathy Trieu"
date: "12/2023"
output: github_document
---

### R Setup

```{r}
rm(list = ls()); gc()

pacman::p_load(tidyverse)
```

### Load Data

```{r loadData}
df = read.csv('data/CPL_Combined_Data.csv')
```

### Missing Values Management

#### Removed all features with 80% or more missing values

```{r removeColumnsWithTooMuchMissingData}
naCount = sort(colSums(is.na(df))) %>% as.data.frame(.)

missingSupervisor = df %>%
  filter(., is.na(LibraryVisits))

df = df %>%
  mutate(naProp = (apply ( X = is.na(df), MARGIN = 1, FUN = mean ) )) %>%
  filter(naProp < .2) %>%
  select(-naProp) %>%
  filter(!is.na(LibraryVisits)) 
```

#### Corrected Column Data Types

```{r dataTypesManagement}
dfFixedTypes = df %>% 
  mutate(across((starts_with("Numof") | 
                   starts_with("Total") |
                   contains("Attendance") |
                   contains("Loans") |
                   contains("Books") |
                   contains("Hours") |
                   contains("Visits") |
                   contains("Reference") |
                   contains("Circulation") | 
                   contains("Population") |
                   contains("Users") |
                   contains("Uses") |
                   contains("Children") |
                   contains("Expenditures") |
                   contains("Income")
                   ), ~gsub("\\,", "", .))) %>%
  mutate(across((contains("Expenditures") | contains("Income")), ~gsub("\\$", "", .))) %>%
  mutate(CIPACompliant = ifelse(CIPACompliant == "No",0,1)) %>%
  apply(.,2, function(x) str_replace_all(string=x, pattern=" ", repl="")) %>% as.data.frame(.)

locationID = dfFixedTypes$Location
year = dfFixedTypes$FiscalYear

dfQuant = dfFixedTypes %>%
  select(., -FSCSID) %>%
  select(., PopulationofTheLegalServiceArea:NumofChildrensPrograms) %>%
  sapply(., as.numeric) %>% as.data.frame(.) %>%
  mutate(Location = locationID,
         Year = year) %>%
  select(Location, Year, everything())
```


#### Median Imputed Missing Data in Quantitative Features

```{r dataImputation}
dfQuant[dfQuant == "-1"] <- NA
dfQuant[dfQuant == "-2"] <- NA

dfQuantImputed = dfQuant %>%
  caret::preProcess(method="medianImpute") %>%
  predict(newdata = dfQuant)

```


#### Checked for Features Without Meaningful Variance

```{r variance}
caret::nearZeroVar(dfQuantImputed, saveMetrics=TRUE)

dfQuantImputed = dfQuantImputed %>% 
  select(-CapitalOutlayIncomefromStateSources,
         -CapitalOutlayIncomefromFederalSources)

```


